### ISSUE TITLE
update vendored argon2

### ISSUE THREAD

**Issue by philtay** [hynek/argon2_cffi#11]
Could you please update the vendored argon2 C code to its latest version (i.e. 20160821 https://github.com/P-H-C/phc-winner-argon2/commit/4844d2fee15d44cb19296ddf36029326d17c5aa3) and release a new version of argon2_cffi? Currently it looks like that the submodule points to a random commit. Thanks.

**Comment by hynek** [comment]
the reason why it doesn’t point directly at 201604016 is that it had a few rather nasty init bugs (see the commits that came right after it).  I could release a new snapshot, but is there anything newsworthy?

**Comment by philtay** [comment]
There are a couple of bugfixes. https://github.com/P-H-C/phc-winner-argon2/compare/00aaa66...4844d2f. As this is a security related library it would be better to use the latest argon2 version. It definitely makes sense to issue a new release even if just to update the vendored dependencies.

**Comment by hynek** [comment]
I’ll push a release once #13 is merged.

**Comment by philtay** [comment]
Thanks a lot

**Comment by Ofekmeister** [comment]
I believe this can now be closed.
