### ISSUE TITLE
PHC string format

### ISSUE THREAD

**Issue by philtay** [hynek/argon2_cffi#12]
The Modular Crypt Format used by `argon2_cffi` doesn't seem to adhere to the official [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) standard. Specifically the `v` parameter is illegal. Using the README's example, the correct hash is `$argon2i$m=512,t=2,p=2$5VtWOO3cGWYQHEMaYGbsfQ$AcmqasQgW/wI6wAHAMk4aQ` (note the missing `$v=19` right after `$argon2i`).

**Comment by hynek** [comment]
The `v` parameter has been introduced in Argon 1.3 which came after the PHC string format repo has been updated.  TBH I’ve never heard of that repo before, maybe you wan to raise an issue over there?  I guess they forgot about it themselves. :)

**Comment by philtay** [comment]
You're right. I'll open an issue upstream.
