### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by paul-100** [hynek/argon2_cffi#15]
Hi,

My installation is failing, I am currently running django 1.10 

![image](https://cloud.githubusercontent.com/assets/9849488/18665239/e934e548-7f2e-11e6-87c8-cb245934710b.png)

**Comment by hynek** [comment]
Did you follow https://argon2-cffi.readthedocs.io/en/stable/installation.html ?

**Comment by paul-100** [comment]
Thanks, problem solved

for those who will encounter this problem install `pip install -U cffi pip setuptools` then `pip install argon2-cffi`
