### ISSUE TITLE
new argon2 release

### ISSUE THREAD

**Issue by philtay** [hynek/argon2_cffi#18]
Please vendor argon2 20161029 (1c4fc41f81f358283755eea88d4ecd05e43b7fd3). Have a look at the [changelog](https://github.com/P-H-C/phc-winner-argon2/blob/master/CHANGELOG.md) to see what's new.

**Comment by hynek** [comment]
Will do before next release.  Currently waiting for virtualenv To be fixed for Python 3.6 and warnings.
