### ISSUE TITLE
some thing is missing in documents(readthedocs.io)

### ISSUE THREAD

**Issue by DariushMazlumi** [hynek/argon2_cffi#30]
hello!
first I want to say thankyou to developers of this great module. I'm using argon2_cffi to write a password manager program (or programm with double m, I don't know which one is correct!). after searching about hash for a week, I finally chosed argon2 for saving master password. then, between argon2i,argon2d and argon2id, I chosed id(is it secure for my use?).then, I wrote my program past few days(part of it), and started debuging it today. after fixing some little bugs, I saw this:
```
 File "passwordmanager.py", line 73, in <module>
    correct_password=verify_password(hash=correct_master_password.encode(),password=entered_master_password.encode())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argon2/_legacy.py", line 64, in verify_password
    return verify_secret(hash, password, type)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argon2/low_level.py", line 171, in verify_secret
    raise VerificationError(error_to_str(rv))
argon2.exceptions.VerificationError: Decoding failed
```
weird! I tried `verify_password()` lots of times in terminal. so I started to understand that what is the problem. after trying `verify_password()` on some argon2id hashes, I tried argon2i hash of password='a' and salt='aaaaaaaa';first time I didn't know that its because I'm using argon2id, and after I realize that, I thought that maybe the default type of `varify_password()` is argon2i and it gives `VerificationError` on other types. so I visited [documentation](https://argon2-cffi.readthedocs.io/en/stable/api.html), but I saw that `verify_password()`, only has `hash` and `password` parameters, not `type`. I tried:
`verify_password(hash=(byte of argon2id hash of password='a' and salt='aaaaaaaa'),password=b'a',type=argon2.Type.ID)`
in terminal. it returned True!(I really didn't expect that it will work!). so I think its better to add `type` parameter for `verify_password()` in document. and finally, please accept my apologize if I'm having any grammar, dictation,e.t.c problem, or I'm saying this in 'issues'(I'm a new user in GitHub and I'm not sure if I should say this in issue or not). and again thanks for this great module! ^_^

**Comment by hynek** [comment]
It seems that you made the understandable mistake of using a [deprecated API](http://argon2-cffi.readthedocs.io/en/latest/api.html#argon2.verify_password) that has a default type set and documented.

The method in the docs you’re referring is not `verify_password()` but `PasswordHasher.verify()` which is also generally speaking the method you should be using.

**Comment by DariushMazlumi** [comment]
thanks @hynek
