### ISSUE TITLE
Argon2id should be the default

### ISSUE THREAD

**Issue by philtay** [hynek/argon2_cffi#33]
Currently `Argon2i` is used as the default algorithm. There are [two published attacks](https://en.wikipedia.org/wiki/Argon2#Cryptanalysis) against it. The [recommended](https://tools.ietf.org/html/draft-irtf-cfrg-argon2-03) and primary variant of `Argon2` is `Argon2id` (also default in libsodium).

**Comment by hynek** [comment]
Hm yeah, I guess I’ll have to build hash flexibility (that’s the wrong word, isn’t it :)) into PasswordHasher and update the docs.

**Comment by philtay** [comment]
Yep!
* Default to `Argon2id`
* `time_cost=1`
* `memory_cost=32 * 1024` (i.e. 32 MiB)
* `parallelism=os.cpu_count() or 2`

**Comment by hynek** [comment]
Yeah I’ll try to read myself thru the RFC on the weekend. I’ve pinged Django about it too since they use the low-level functions.

**Comment by hynek** [comment]
I have started working on that in #34 but I don’t think I’m comfortable to change the other default parameters .

**Comment by philtay** [comment]
`memory_cost` is arbitrary, the others are sane defaults. A `time_cost > 1` doesn't make much sense for password hashing and having `parallelism = number of cores` is quite obvious. Anyway, more than hardcoded default arguments, we need an helper function that, given a time constraint, returns optimal parameters. That's a good one: https://gitlab.com/cryptsetup/cryptsetup/blob/master/lib/crypto_backend/pbkdf_check.c#L202
