### ISSUE TITLE
invalid ELF header (Apache 2.4, mod_wsgi, python 2.7.12)

### ISSUE THREAD

**Issue by DudkinON** [hynek/argon2_cffi#38]
I use argon2-cffi==18.1.0 with framework flask==1.0.2, on Server Ubuntu 16.04 and Apahe 2.4 with mod_wsgi. When I try to run page I have Internal Server Error with status code 500
in Apach2 error.log:
ImportError: /var/www/fra/env/lib/python2.7/site-packages/argon2/_ffi.so: invalid ELF header

**Comment by hynek** [comment]
Uh that sounds like the wrong wheel got installed or something? How did you build the virtualenv?

**Comment by DudkinON** [comment]
Sorry for creating this issue, I solved it by removing AWS instance and configuring everything again. 
I build the virtualenv with following commands: 

`sudo apt-get install python-pip`
`python -m pip install --user virtualenv`
`sudo python -m virtualenv env`
`source env/bin/activate`
`sudo pip install -r requirements.txt`

I think the problem was in installation Apache mod_wsgi, for some reason mod_wsgi was installed incorrectly.

Sorry again for the inconvenience.
