### ISSUE TITLE
Some parameter combinations cause a password to not validate against itself

### ISSUE THREAD

**Issue by DRMacIver** [hynek/argon2_cffi#4]
Hi, I read [Storing Passwords in a Highly Parallelized World](https://hynek.me/articles/storing-passwords/) and thought it might be interesting to apply [Hypothesis](http://hypothesis.readthedocs.org/) to testing your argon2 bindings.

This resulted in the following example:

```python
    def test_a_password_verifies(self):
        ph = PasswordHasher(
            time_cost=1, parallelism=1,
            memory_cost=8,
            hash_len=4, salt_len=8,
        )
        password = ''
        hash = ph.hash(password)
        assert ph.verify(hash, password)
```
i.e. we set up a hasher with some parameters, then hash a password and validate it against itself. This test passes correctly with the default parameter values but fails with these ones.

This fails with "argon2.exceptions.VerificationError: Decoding failed"

(The fact that the password is empty appears to not be significant - it still fails with e.g. '0')

I'm insufficiently familiar with the problem space to know whether this is likely to be an issue in the bindings, the underlying library, or indeed just me doing something subtly wrong, so I thought I'd pass this over to you.

I am also happy to submit a pull request to add the original Hypothesis based tests (which just tries a large number of examples like the above) to your suite if you'd like me to.

**Comment by hynek** [comment]
Hi David,

[I am already using Hypothesis!](https://github.com/hynek/argon2_cffi/blob/master/tests/test_low_level.py#L7-L8) :)

I’m just not using it enough.  :(  Mostly because I hadn’t the time to learn it properly.

I have opened an issue on the Argon2 bug tracker because I could reproduce it in their C client too.

**Comment by DRMacIver** [comment]
So you are! Sorry, I'd missed that. I'd looked at test_password_hasher but not any of the others.

**Comment by DRMacIver** [comment]
FWIW, it's not just digest sizes < 12. The following combination also fails:

```
password='', time_cost=1, parallelism=1, memory_cost=8, hash_len=513, salt_len=8
```

**Comment by DRMacIver** [comment]
Here's the full test if you want to try it out yourself:

```python
from argon2 import PasswordHasher

from hypothesis import given, assume
import hypothesis.strategies as st


class TestPasswordHasherWithHypothesis(object):
    @given(
        password=st.text(),
        time_cost=st.integers(1, 10),
        parallelism=st.integers(1, 10),
        memory_cost=st.integers(8, 2048),
        hash_len=st.integers(12, 1000),
        salt_len=st.integers(8, 1000),
    )
    def test_a_password_verifies(
        self,
        password, time_cost, parallelism, memory_cost, hash_len, salt_len,
    ):
        assume(parallelism * 8 <= memory_cost)
        ph = PasswordHasher(
            time_cost=time_cost, parallelism=parallelism,
            memory_cost=memory_cost,
            hash_len=hash_len, salt_len=salt_len,
        )
        hash = ph.hash(password)
        assert ph.verify(hash, password)
```

**Comment by DRMacIver** [comment]
This also breaks:

```
time_cost=1, parallelism=1, memory_cost=8, hash_len=12, salt_len=513
```

It looks like this may be a separate issue where salt and hash lengths > 512 do not work. If I restrict them to be <= 512 the test passes.

**Comment by technion** [comment]
There have been a several relevant upstream bugs that now have fixes in place. Would suggest pulling in the latest and identifying what does (if anything) and doesn't still exist.

**Comment by hynek** [comment]
@technion Updating the bindings led to a rather weird test failure: it seems like `argon2_verify()` will succeeds if a correct hash with a wrong Argon2 type are passed.  Do you know anything about that?  It’s this [test](https://github.com/hynek/argon2_cffi/blob/045e11063137de8f22216768041b2c3b6a0a06af/tests/test_low_level.py#L187-L192) (and it's legacy sibling).

**Comment by hynek** [comment]
Ouch, I’ve deleted the comment.  Apparently I’ve run into a nasty new bug.  Contacting the authors privately.

**Comment by hynek** [comment]
The latest revision of the bindings appear to have fixed all of this.

I’ve added a [similar test](https://github.com/hynek/argon2_cffi/blob/675576a6340f331cb84c1d07fa83db75fdb66afa/tests/test_low_level.py#L213-L239) as a smoke test if they break something again.

The bindings introduced other breakage but that’s something for other tickets.
