### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ofek** [hynek/argon2_cffi#40]
@hynek Hello again! When you get a chance, could you please trigger a new release that ships compiled wheels for Python 3.7? 🙏

**Comment by hynek** [comment]
I need to finish #41 first which I’ve been working/procrastinating on since April basically. :|

**Comment by hynek** [comment]
18.2.0 is on PyPI: https://pypi.org/project/argon2_cffi/

I hope the new abi3 wheels will prevent these kind of issues in the future. 🤞
