### ISSUE TITLE
PyPI source code link is broken

### ISSUE THREAD

**Issue by HacKanCuBa** [hynek/argon2_cffi#45]
In [PyPi's package page](https://pypi.org/project/argon2_cffi/), the source code URL pointing to this repo has a typo, so does the bug tracker link pointing to this repo's issues: it has a dash instead of an underscore.

**Comment by hynek** [comment]
Yeah that has been fixed in 39d8a8b7e37cac0b07490dc631f7d36eaf938824 but there was no new release since then due to lack of notable features.

I'll leave this bug open until the next release I guess.
