### ISSUE TITLE
hash generated on 18.3.0/19.1.0 fails to verify on 18.1.0

### ISSUE THREAD

**Issue by hmoffatt** [hynek/argon2_cffi#47]
I'm generating hashes with 18.3.0 and 19.1.0 and they're failing to validate with 18.1.0, with a decoding error. I thought this might be due to the change to argon2di by default, but even forcing d format doesn't make a difference. Forcing i format works though.

On 19.1.0:

```
>>> import argon2
>>> from argon2 import PasswordHasher
>>> ph=argon2.PasswordHasher(type=argon2.Type.D)
>>> ph.hash('foo')
u'$argon2d$v=19$m=102400,t=2,p=8$+dkJA3heBNgzLt4ZJ244mQ$vy3GwRpCXVty3x/W4VjMqQ'
```

Then verify on 18.1.0:

```
>>> ph.verify(u'$argon2d$v=19$m=102400,t=2,p=8$+dkJA3heBNgzLt4ZJ244mQ$vy3GwRpCXVty3x/W4VjMqQ', 'foo')
Traceback (most recent call last):
...
argon2.exceptions.VerificationError: Decoding failed
```

Maybe this is a known incompatibility but I didn't see it in the changelog.

**Comment by hynek** [comment]
Hash agility wasn't added until 18.2.0. Before it was always Type.I.

[The Changelog for 18.2](https://github.com/hynek/argon2_cffi/blob/master/CHANGELOG.rst#1820-2018-08-19) mentions that the default changed and that the PH has gained agility.

If you need to to check hashes from 18.2+ using 18.1, I suppose you can use the low-level functions that allow to force parameters?

**Comment by hmoffatt** [comment]
Ah sorry, I didn't know what "hash agility" referred to.

**Comment by hmoffatt** [comment]
Sorry, it's clear now. Thanks.
