### ISSUE TITLE
`enum34` dependency breaks some installs

### ISSUE THREAD

**Issue by murrple-1** [hynek/argon2_cffi#48]
First off, I'm not convinced if this should be a bug report here, but at the very least, I can suggest it.

Essentially, it seems that installing `enum34` in environments of Python 3.6 and above can break certain codebases (see: https://stackoverflow.com/q/43124775), including mine. It seems `enum34` is often loaded/imported ahead of the standard-library's `enum`, and the APIs have slightly diverged since Python 3.4.

Now, you may be thinking, "I know, that's why there's a check in `setup.py`" (see: https://github.com/hynek/argon2_cffi/blob/master/setup.py#L98). *However*, this sort of protection seems to not work really well with the more "modern" packaging solutions, like `pipenv` and `poetry` (see: https://github.com/pypa/pipenv/issues/924, https://github.com/sdispater/poetry/issues/758), because the python version running the `setup.py` may not be the same version being deployed, and as they generate consistent lockfiles, regardless of the running python version.

It seems a nuisance, as the onus maybe should be on the package managers to figure it out. However, I would like to suggest/request that

a) the support for pre-3.4 python versions be dropped by removing the dependency on `enum34`, or

b) the package be split between a `enum34` installable and non-`enum34` installable. I think this can be achieved pretty easily with the `extras_require` argument in `setuptools`, such that
```
pip install argon2-cffi
```
would install without `enum34`, and
```
pip install argon2-cffi[enum34]
```

would install with `enum34`. If it helps, [this project](https://pypi.org/project/qrcode/) showcases the usecase in action, and [this code](https://github.com/lincolnloop/python-qrcode/blob/master/setup.cfg#L43) shows how it's done.

Or,

c) take advantage of environment markers in `setup.py` instead. I don't fully understand what that means or entails, so I have a hard time recommending it, but [this comment](https://github.com/sdispater/poetry/issues/758#issuecomment-453864964) seems to suggest it as an alternative to doing a `sys.version_info` check.

If a) or b) sound logical, I can submit a PR.

**Comment by murrple-1** [comment]
An example of the issue in action is available here: https://travis-ci.org/murrple-1/pipenv-issue-3

I have also opened an issue with pipenv to see if there is a better workaround that I missed.

**Comment by hynek** [comment]
Hmmm, so what triggers this problem for you is this:

```
 No binaries permitted for argon2-cffi
```

because argon2-cffi goes for great lengths to build wheels for all relevant platforms and the requirements should be encoded correctly in the wheels.

I suppose I need to additionally add protective markers for cases like yours.

**Comment by hynek** [comment]
I think 8eed81aaee920a8b20442b2d8e784b7c01e62dc6 should fix it. Is there a way for you to test against master?

**Comment by murrple-1** [comment]
Yes, that appears to work for me, and (if it means anything from a rando from the internet) I like the elegance of that solution.

Per your comment about the `No binaries permitted for argon2-cffi`, I was creating that contrived environment in Travis CI (see `export PIP_NO_BINARY=argon2-cffi`. I am building/testing my project on Cygwin, which is one of the few environments where this sort of issue would arise.

**Comment by hynek** [comment]
Cool, thanks!
